# Generated by Django 4.2.6 on 2024-02-10 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_brand_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Cars',
            },
        ),
    ]
