# Generated by Django 4.2.6 on 2024-01-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
