# Generated by Django 5.0.3 on 2024-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Customizations', editable=False, max_length=220)),
                ('main_image', models.ImageField(null=True, upload_to='Images/Main_Images')),
            ],
            options={
                'verbose_name_plural': 'Customizations',
            },
        ),
    ]
