# Generated by Django 5.0.3 on 2024-03-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='main_image',
        ),
        migrations.AddField(
            model_name='customization',
            name='listing_image_desktop',
            field=models.ImageField(null=True, upload_to='Images/Listing_Images_desktop'),
        ),
        migrations.AddField(
            model_name='customization',
            name='listing_image_mobile',
            field=models.ImageField(null=True, upload_to='Images/Listing_Images_mobile'),
        ),
        migrations.AddField(
            model_name='customization',
            name='main_large_heading',
            field=models.CharField(default='Rent Your Dream Car', max_length=220),
        ),
        migrations.AddField(
            model_name='customization',
            name='main_screen_image_desktop',
            field=models.ImageField(null=True, upload_to='Images/Main_Images_Desktop'),
        ),
        migrations.AddField(
            model_name='customization',
            name='main_screen_image_mobile',
            field=models.ImageField(null=True, upload_to='Images/Main_Images_Mobile'),
        ),
        migrations.AddField(
            model_name='customization',
            name='main_small_heading',
            field=models.CharField(default='Find Cars For Rent Near You', max_length=220),
        ),
        migrations.AddField(
            model_name='customization',
            name='saved_car_image_desktop',
            field=models.ImageField(null=True, upload_to='Images/Listing_Images_desktop'),
        ),
        migrations.AddField(
            model_name='customization',
            name='saved_car_image_mobile',
            field=models.ImageField(null=True, upload_to='Images/Listing_Images_mobile'),
        ),
    ]
