# Generated by Django 4.2.6 on 2024-02-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0012_car_is_deleted_car_monthly_rent_car_weekly_rent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='rent', unique=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('office', 'Office')], max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rents',
            },
        ),
    ]
