# Generated by Django 4.2.6 on 2024-02-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='number_of_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='period',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Rented_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent.rent')),
            ],
            options={
                'verbose_name_plural': 'Rented Cars',
            },
        ),
    ]
