# Generated by Django 4.2.6 on 2024-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rent_created_at_rent_number_of_period_rent_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='rent',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('Pickup', 'Pickup'), ('Home Delivery', 'Home Delivery')], max_length=50, null=True),
        ),
    ]
