# Generated by Django 4.2.6 on 2024-02-25 11:30

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rent_rent_rent_total_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='12345', length=10, max_length=30, prefix='', unique=True),
        ),
    ]
