# Generated by Django 4.2.6 on 2024-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_rent_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented_car',
            name='over_due_charges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rented_car',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Returned', 'Returned'), ('In Hand', 'In Hand'), ('Over Dued', 'Over Dued'), ('To be delivered', 'To be delivered'), ('To be Picked', 'To be Picked')], max_length=50, null=True),
        ),
    ]
