# Generated by Django 4.2.6 on 2024-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_rented_car_over_due_charges_rented_car_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_car',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Returned', 'Returned'), ('In Hand', 'In Hand'), ('Over Dued', 'Over Dued'), ('To be delivered', 'To be delivered'), ('To be Picked', 'To be Picked'), ('Finished', 'Finished')], max_length=50, null=True),
        ),
    ]
