# Generated by Django 4.2.6 on 2024-03-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_rented_car_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_car',
            name='rent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rented', to='rent.rent'),
        ),
    ]
