# Generated by Django 5.0.3 on 2024-03-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_alter_rented_car_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='extended_rent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Extended_Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=50, null=True)),
                ('number_of_period', models.PositiveIntegerField(blank=True, null=True)),
                ('extended_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='rent.rent')),
            ],
            options={
                'verbose_name_plural': 'Extended Rents',
            },
        ),
    ]
