# Generated by Django 5.0.3 on 2024-03-21 22:04

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_extended_rent_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_rent',
            name='erid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='6789', length=10, max_length=30, null=True, prefix='', unique=True),
        ),
    ]
