# Generated by Django 5.0.3 on 2024-03-22 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_extended_rent_erid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_rent',
            name='rent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='rent.rent'),
        ),
    ]
