# Generated by Django 4.2.6 on 2024-01-26 06:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_car_specification_alter_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fuel Types',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Transmissions',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='specification',
        ),
        migrations.AlterField(
            model_name='carimages',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car'),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_size', models.DecimalField(decimal_places=2, max_digits=2)),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('condition', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(10.0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cars.car')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.fuel_type')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission')),
            ],
            options={
                'verbose_name_plural': 'Specifications',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('review', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Air_Conditioner', models.BooleanField(default=False)),
                ('Digital_Odometer', models.BooleanField(default=False)),
                ('Heater', models.BooleanField(default=False)),
                ('Leather_Seats', models.BooleanField(default=False)),
                ('Panoramic_Moonroof', models.BooleanField(default=False)),
                ('Tachometer', models.BooleanField(default=False)),
                ('Touchscreen_Display', models.BooleanField(default=False)),
                ('Antilock_Braking', models.BooleanField(default=False)),
                ('Brake_Assist', models.BooleanField(default=False)),
                ('Child_Safety_Locks', models.BooleanField(default=False)),
                ('Driver_Air_Bag', models.BooleanField(default=False)),
                ('Power_Door_Locks', models.BooleanField(default=False)),
                ('Stability_Control', models.BooleanField(default=False)),
                ('Traction_Control', models.BooleanField(default=False)),
                ('Fog_Lights_Front', models.BooleanField(default=False)),
                ('Rain_Sensing_Wiper', models.BooleanField(default=False)),
                ('Rear_Spoiler', models.BooleanField(default=False)),
                ('Windows_Electric', models.BooleanField(default=False)),
                ('Android_Auto', models.BooleanField(default=False)),
                ('Bluetooth', models.BooleanField(default=False)),
                ('HomeLink', models.BooleanField(default=False)),
                ('Power_Steering', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
    ]
