# Generated by Django 4.2.6 on 2024-01-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_fuel_type_transmission_remove_car_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cars.car'),
        ),
    ]
