# Generated by Django 4.2.6 on 2024-01-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_features_car_alter_specification_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(null=True, upload_to='Car/All_Images/{{car.name}}_{{car.id}}'),
        ),
    ]
