# Generated by Django 4.2.6 on 2024-01-26 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='condition',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(4.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='specification',
            name='engine_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
