# Generated by Django 4.2.6 on 2024-01-27 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='max_speed_in_km_per_h',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
