# Generated by Django 4.2.6 on 2024-01-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_specification_max_speed_in_km_per_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='no_of_times_rented',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
