# Generated by Django 4.2.6 on 2024-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_is_deleted_car_monthly_rent_car_weekly_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
