# Generated by Django 5.0.3 on 2024-03-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='Reviews/images'),
        ),
    ]
