# Generated by Django 5.0.3 on 2024-03-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Reviews/images'),
        ),
    ]
