# Generated by Django 5.0.3 on 2024-04-03 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
